package TestSuite;


import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class winit {


    // Generated by Selenium IDE


      //  private WebDriver driver;
      //  private Map<String, Object> vars;
      //  JavascriptExecutor js;
//
//        @BeforeTest
//        public void setUp() {
//            WebDriverManager.firefoxdriver().driverVersion("0.33.0").setup();
//            FirefoxDriver driver = new FirefoxDriver();
//            js = (JavascriptExecutor) driver;
//            vars = new HashMap<String, Object>();
//        }
//
//        @AfterTest
//        public void tearDown() {
//            driver.quit();
//        }

        @Test()
        public void createreturnorder() throws InterruptedException {
            //WebDriverManager.firefoxdriver().driverVersion("0.33.0").setup();
            //FirefoxDriver driver = new FirefoxDriver();
            //WebDriverManager.chromedriver().setup();
            //System.setProperty("webdriver.chrome.driver", "C:\\Users\\ramkr\\IdeaProjects\\TestNGParameterization\\chromedriver.exe");
            WebDriver driver = new ChromeDriver();
            driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
            driver.get("https://dev-arlavansales.winitsoftware.com/pages/Login.aspx");
            driver.manage().window().setSize(new Dimension(1296, 688));
            driver.findElement(By.id("txtUsername")).sendKeys("ksaadmin");
            driver.findElement(By.id("txtPassword")).click();
            driver.findElement(By.id("txtPassword")).sendKeys("1234");
            driver.findElement(By.id("chkRememberme")).click();
            driver.findElement(By.cssSelector("#btnLogin > img")).click();
            Thread.sleep(2000);
            driver.findElement(By.id("chk_KSA Sales Super User_1")).click();
            driver.findElement(By.id("btnNavigate")).click();
            Thread.sleep(5000);
            driver.findElement(By.cssSelector("#ancSfaTransactions > span:nth-child(1)")).click();
            driver.findElement(By.linkText("PreSeller Return Orders")).click();
            Thread.sleep(3000);
            driver.findElement(By.id("cphContent_CreateOrderDiv")).click();
            Thread.sleep(3000);
            driver.findElement(By.cssSelector("#cphContent_updatepanel1 > div:nth-child(1) > button:nth-child(2) > span:nth-child(2)")).click();
            driver.findElement(By.cssSelector("body > div:nth-child(15) > div > div > input[type=search]")).click();
            driver.findElement(By.xpath("//*[@id=\"ng-app\"]/body/div[9]/div/div/input")).sendKeys("96600047");
            driver.findElement(By.xpath("/html/body/div[9]/ul/li[4]/label/span")).click();
            driver.findElement(By.id("cphContent_txtDeliveryDate")).click();
            //driver.findElement(By.id("cphContent_ceDeliveryDate_day_1_3")).click();
            driver.findElement(By.id("cphContent_txtDeliveryDate")).sendKeys("Jul 5, 2023");
            driver.findElement(By.id("cphContent_txtCutoffDate")).click();
            driver.findElement(By.id("cphContent_CalendarExtender1_day_2_4")).click();
            driver.findElement(By.id("cphContent_txtCutoffDate")).sendKeys("Jul 13, 2023");
            driver.findElement(By.id("cphContent_txtPONumberxyz")).click();
            driver.findElement(By.id("cphContent_txtPONumberxyz")).sendKeys("test130");
            driver.findElement(By.id("cphContent_btnAddEdit")).click();
            Thread.sleep(3000);
            driver.findElement(By.linkText("Add Items")).click();
            driver.findElement(By.id("item_991450")).click();
            driver.findElement(By.id("item_990139")).click();
            driver.findElement(By.id("item_991449")).click();
            driver.findElement(By.id("txtitemsearch")).click();
            driver.findElement(By.id("txtitemsearch")).sendKeys("991449");
            Thread.sleep(2000);
            driver.findElement(By.id("item_991449")).click();
            driver.findElement(By.id("btnAddItemModel")).click();
            driver.findElement(By.cssSelector(".gridrow:nth-child(1) .NoClass_savedfoctxt")).click();
            driver.findElement(By.cssSelector(".gridrow:nth-child(1) .NoClass_savedfoctxt")).sendKeys("1");
           // driver.findElement(By.cssSelector(".gridrow:nth-child(2) .NoClass_savedfoctxt")).click();
           // driver.findElement(By.cssSelector(".gridrow:nth-child(1) .ddlReasons")).click();

            {
                WebElement dropdown = driver.findElement(By.cssSelector(".gridrow:nth-child(1) .ddlReasons"));
                Thread.sleep(2000);
                dropdown.findElement(By.xpath("//option[. = 'Expiry']")).click();
            }
            driver.findElement(By.cssSelector(".gridrow:nth-child(1) .ddlSubReasons")).click();
            {
                WebElement dropdown = driver.findElement(By.cssSelector(".gridrow:nth-child(1) .ddlSubReasons"));
                Thread.sleep(2000);
                dropdown.findElement(By.xpath("//option[. = 'Blown up']")).click();
            }
            driver.findElement(By.cssSelector(".gridrow:nth-child(2) .NoClass_savedfoctxt")).click();
            driver.findElement(By.cssSelector(".gridrow:nth-child(2) .NoClass_savedfoctxt")).sendKeys("1");
            //driver.findElement(By.cssSelector(".gridrow:nth-child(2) .ddlReasons")).click();
            //driver.findElement(By.cssSelector(".gridrow:nth-child(2) .ddlSubReasons")).click();
            {
                WebElement dropdown = driver.findElement(By.cssSelector(".gridrow:nth-child(2) .ddlSubReasons"));
                Thread.sleep(2000);
                dropdown.findElement(By.xpath("//option[. = 'Leakages']")).click();
            }
            driver.findElement(By.cssSelector(".gridrow:nth-child(3) .NoClass_savedfoctxt")).click();
            driver.findElement(By.cssSelector(".gridrow:nth-child(3) .NoClass_savedfoctxt")).sendKeys("2");
            driver.findElement(By.cssSelector(".gridrow:nth-child(3) .ddlSubReasons")).click();
            {
                WebElement dropdown = driver.findElement(By.cssSelector(".gridrow:nth-child(3) .ddlSubReasons"));
                Thread.sleep(2000);
                dropdown.findElement(By.xpath("//option[. = 'Color Change']")).click();
            }
            driver.findElement(By.id("chkselect_990139_PCS")).click();
            driver.findElement(By.id("chkselect_991449_PCS")).click();
            driver.findElement(By.id("chkselect_991450_PCS")).click();
            driver.findElement(By.cssSelector(".container")).click();
            driver.findElement(By.cssSelector(".gridrow:nth-child(2) .lblRemove")).click();
            driver.findElement(By.id("cphContent_btnFinalize")).click();
            Thread.sleep(5000);
            driver.findElement(By.cssSelector(".selReport_NoClass:nth-child(5)")).click();
//            driver.findElement(By.linkText("Cust Ref No")).click();
//            {
//                WebElement element = driver.findElement(By.id("divLoader"));
//                Actions builder = new Actions(driver);
//                builder.doubleClick(element).perform();
//            }
        }
    }



